trigger: none
pr: none

schedules:
  - cron: "0 2 * * *"
    displayName: "Daily Dependabot Scan"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: ubuntu-latest

variables:
  - group: appsec-dependabot

steps:
  - checkout: self

  - task: Docker@2
    displayName: "Build Dependabot Core Image"
    inputs:
      command: build
      dockerfile: dependabot/Dockerfile
      repository: dependabot-core
      tags: latest
      arguments: --progress=plain

  # Scan appsec-renovate-bot
  - task: Docker@2
    displayName: "Scan: appsec-renovate-bot"
    inputs:
      command: run
      arguments: |
        --rm
        -e AZURE_ACCESS_TOKEN=$(ADO_DEPENDABOT_PAT)
        -e AZURE_ORG=TEXTOCORP
        -e PACKAGE_MANAGER=npm
        -e PROJECT_PATH=TEXTOCORP/InfoSec/_git/appsec-renovate-bot
        -e DIRECTORY_PATH=/
        dependabot-core:latest
    continueOnError: true

  # Scan appsec-test
  - task: Docker@2
    displayName: "Scan: appsec-test"
    inputs:
      command: run
      arguments: |
        --rm
        -e AZURE_ACCESS_TOKEN=$(ADO_DEPENDABOT_PAT)
        -e AZURE_ORG=TEXTOCORP
        -e PACKAGE_MANAGER=npm
        -e PROJECT_PATH=TEXTOCORP/InfoSec/_git/appsec-test
        -e DIRECTORY_PATH=/
        dependabot-core:latest
    continueOnError: true

  # Add more repos as needed by copying the Docker@2 task above
